apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fveec2l8g-go-gitops
  description: This is GitOps manifest for fveec2l8g-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=fveec2l8g-go
    backstage.io/kubernetes-id: fveec2l8g-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fveec2l8g-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fveec2l8g-go
